### ISSUE TITLE
Import Javascripts of bootstrap 4

### ISSUE THREAD

**Issue by GELight** [kaermorchen/ember-cli-bootstrap-4#12]
Hi,

Can you write a code snippet for the correct import of the Javascripts of bootstrap 4?

I putted this line in my ember-cli-build.js:

`
app.import('bootstrap/dist/js/bootstrap.js');
`

... but the following error is occurred:

`
Error: ENOENT: no such file or directory, open 'C:\projects\ember-application-ui\tmp\source_map_concat-input_base_path-G7HZxLFz.tmp\node_modules\bootstrap\dist\js\bootstrap.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
`

What's wrong in my app?

Greetings,
Mario

**Comment by kaermorchen** [comment]
You don't need import bootstrap.js. It is already imported from the addon.

Feel free to reopen it.

**Comment by GELight** [comment]
Hi kaermorchen,

Unfortunatelly this plugin do not import the javascripts automatically in my app.
I installed ths plugin in my app and the javascripts from the bootstrap components is not in function.

Greetings, Mario
