### ISSUE TITLE
not working with fastboot 1.0.2

### ISSUE THREAD

**Issue by bantic** [kaermorchen/ember-cli-bootstrap-4#17]
Fastboot [no longer provides the env `EMBER_CLI_FASTBOOT` variable](https://github.com/ember-fastboot/ember-cli-fastboot#disabling-incompatible-dependencies), so the [`enabled` flags in index.js](https://github.com/kaermorchen/ember-cli-bootstrap-4/blob/master/index.js#L29) are true for both popper.js and bootstrap.js even when run via fastboot.

**Comment by artinboghosian** [comment]
#18 Should fix the issue

**Comment by kaermorchen** [comment]
@artinboghosian thank you!

**Comment by artinboghosian** [comment]
@kaermorchen no problem 😄
