### ISSUE TITLE
Way to import part of JavaScript modules instead of whole Bootstrap?

### ISSUE THREAD

**Issue by Kuzirashi** [kaermorchen/ember-cli-bootstrap-4#20]
Hello, is there a way to import partial JavaScript of BS instead of whole bootstrap.js file?

**Comment by kaermorchen** [comment]
Nope. I think I can do it later.

**Comment by kaermorchen** [comment]
Check out the latest version (0.4.1). It have the [config](https://github.com/kaermorchen/ember-cli-bootstrap-4#javascript-components) for you.

**Comment by Kuzirashi** [comment]
Nice. Thank you!!! So quick response! :)
