### ISSUE TITLE
No glyphicon rendered

### ISSUE THREAD

**Issue by GELight** [kaermorchen/ember-cli-bootstrap-4#24]
Hi,

I work on a new page with your ember addon for bootstrap 4 but I do not see any glyphicons in my navigation. ( navbar-toggler-icon )

Are there any steps after install your addon to see all correctly?

I work with ember-cli: 2.17.1 and node: 6.11.2.

Greetings,
Mario

**Comment by kaermorchen** [comment]
Hi, I will check it.

**Comment by kaermorchen** [comment]
Where did you find glyphicons in bootstrap 4?

**Comment by GELight** [comment]
Hi ... I think you can ignore and remove my issue.
It was a css problem. Your addon should be work correctly :)

Best regards,
Mario
