### ISSUE TITLE
Using the newest bootstrap version not possible

### ISSUE THREAD

**Issue by GELight** [kaermorchen/ember-cli-bootstrap-4#25]
Hi,

Currently there will be included the alpha version of bootstrap in your addon >>> https://v4-alpha.getbootstrap.com/components/input-group/

It's possible to use the newest bootstrap version ( https://getbootstrap.com ) with your addon?

Best regards,
Mario

**Comment by kaermorchen** [comment]
Hi.

Current version of the bootstrap of the this addon is 4.0.0-beta.2 You can change version in package.json of you project.

I will update to v4.0.0-beta.3 soon

**Comment by kaermorchen** [comment]
I have updated it to v4.0.0-beta.3.

Fill free to reopen it, if do you need.
