### ISSUE TITLE
0.5 does not run in fastboot

### ISSUE THREAD

**Issue by medokin** [kaermorchen/ember-cli-bootstrap-4#29]
`ReferenceError: $ is not defined`

**Comment by kaermorchen** [comment]
Are you sure it is error from ember-cli-bootstrap-4?

**Comment by medokin** [comment]
It worked fine with v3.* 
I guess it comes from its sidekick: popper.js, but there is an ember wrapper: https://github.com/kybishop/ember-popper

Maybe a simple replacement will do. I'll give it a shot this week and report back.

**Comment by medokin** [comment]
Update: The Error comes from `Bootstrap (v4.0.0): util.js`

**Comment by kaermorchen** [comment]
I have added compatibility for fastboot. Check it out in latest version (v0.5.3)

Feel free to reopen if do you need.
