### ISSUE TITLE
Undefined variable: "$theme-colors".

### ISSUE THREAD

**Issue by MrChriZ** [kaermorchen/ember-cli-bootstrap-4#31]
I've just tried to import Bootstrap Utilities but I've ran into the error:

> Undefined variable: "$theme-colors".

Just to confirm the steps I followed:
I installed using:
` ember install ember-cli-bootstrap-4`
and then I added the following to my app.scss
`@import "ember-cli-bootstrap-4/utilities";`

**Comment by kaermorchen** [comment]
Try add 
```
@import "ember-cli-bootstrap-4/functions";
@import "ember-cli-bootstrap-4/variables";
@import "ember-cli-bootstrap-4/mixins";
```
before 
```
@import "ember-cli-bootstrap-4/utilities";
```

**Comment by MrChriZ** [comment]
Ah that makes sense.  Thanks
