### ISSUE TITLE
hoek depency "Prototype pollution"

### ISSUE THREAD

**Issue by well0nez** [kaermorchen/ember-cli-bootstrap-4#32]
Hi, iam using the latest ember-cli-bootstrap-4 0.5.9 module with the latest nodejs version.

It looks like the hoek version was not updated, please have a look:

Npm audit logfile:
https://pastebin.com/m1NjQvzw

Is some update planned?

npm -v
6.0.1

nodejs -v
v10.1.0

**Comment by kaermorchen** [comment]
Hi.

This problem from `node-sass` [#2355](https://github.com/sass/node-sass/issues/2355), try use [these](https://github.com/sass/node-sass/issues/2288) solutions

**Comment by well0nez** [comment]
as i thought.

thank you !
