### ISSUE TITLE
Broken Imports in Yarn Workspaces

### ISSUE THREAD

**Issue by ahawkins** [kaermorchen/ember-cli-bootstrap-4#34]
I'm reworking a monorepo project to use yarn workspaces. This means that related dependencies may not be in assumed locations. I suggest this addon use something like https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L176-L187 to resolve dependency paths. Otherwise this addon's imports for scss and js will fail. 

Example of problematic import: https://github.com/kaermorchen/ember-cli-bootstrap-4/blob/master/index.js#L52

**Comment by kaermorchen** [comment]
I have refactored some code. Could you please try to use the latest version (0.8)

**Comment by kaermorchen** [comment]
Closing this ticket. Feel free to reopen if the problem still exists.
