### ISSUE TITLE
[0.8.0] found an unknown transformation name `fastbootTransform`

### ISSUE THREAD

**Issue by olleolleolle** [kaermorchen/ember-cli-bootstrap-4#35]
Hello!

Today I had dependabot make an upgrade from 0.7.0 to 0.8.0. I had an issue.

> while import `node_modules/popper.js/dist/umd/popper.js`: found an unknown transformation name `fastbootTransform`. Available transformNames are: `amd`,`cjs`

## Things I tried

- include the package "fastboot-transform": "^0.1.3" as a depdendency
- search a lot among other issues

## Things I suspected

- Did this https://github.com/kaermorchen/ember-cli-bootstrap-4/commit/17de8af54cd5534350fc52b3f77abce3a32a2ad7 lead to a situation where `included` could have problems?

**Comment by olleolleolle** [comment]
Private project, 3.6.0

**Comment by kaermorchen** [comment]
I cannot catch this error. But I have updated the ember-cli version to 3.6 maybe it can help

**Comment by olleolleolle** [comment]
I still have the issue with 0.9.0 but my debugging is not yet at its end. Many dependent components.

**Comment by nanderss** [comment]
@olleolleolle Hi colleague! This was an issue that came from another dependency in our project. We're solving this as we speak, so I think this issue can be closed.

@kaermorchen Me and @olleolleolle work at the same place, this issue is resolved and can be closed.
