### ISSUE TITLE
Does not work with Octane blueprint

### ISSUE THREAD

**Issue by axyxnz** [kaermorchen/ember-cli-bootstrap-4#37]
**Steps to reproduce:**
1. Run `ember new my-app -b @ember/octane-app-blueprint`
2. Go into `my-app` folder and run `npm install`
3. Run `ember install ember-cli-bootstrap-4`
4. Run `ember serve`

You will get following errors:

```
util.js:65 Uncaught TypeError: Cannot read property 'fn' of undefined
    at setTransitionEndSupport (util.js:65)
    at util.js:168
    at util.js:10
    at util.js:11
setTransitionEndSupport @ util.js:65
(anonymous) @ util.js:168
(anonymous) @ util.js:10
(anonymous) @ util.js:11
loader.js:247 Uncaught Error: Could not find module `ember-resolver` imported from `webapp-ember-coffee/resolver`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at app-boot.js:3
```

**Edit:** Above error (`Cannot read property 'fn' of undefined at setTransitionEndSupport`) happens due to JQuery not getting loaded/initialized before Bootstrap's JS.

**Comment by kaermorchen** [comment]
If you don't need bootstrap's javascript files, [turn them off](https://github.com/kaermorchen/ember-cli-bootstrap-4#javascript-components).

**Comment by techdragon** [comment]
I tried turning them off in my Octane test, and I just triggered a jQuery check warning. 
`Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.`

**Comment by kaermorchen** [comment]
My test a new octane project with ember-cli-bootstrap-4 works fine.

@techdragon How can I reproduce your warning?

**Comment by kaermorchen** [comment]
Closing this ticket. Feel free to reopen if the problem still exists.
