### ISSUE TITLE
Compatibility With Other Pre-processors

### ISSUE THREAD

**Issue by drewcovi** [kaermorchen/ember-cli-bootstrap-4#4]
Is there any way this addon can be integrated more akin to how ember-bootstrap integrates? I believe it exports compiled css rather than providing scss for use in a project.

One could still decide which packages to include within the config/environment.js and it wouldn't prevent developers from opting instead for **stylus** or other options.

**Comment by kaermorchen** [comment]
I don't understand how can I do this.

Feel free to reopen it.
