### ISSUE TITLE
Bootstrap 4 - Javascripts missed

### ISSUE THREAD

**Issue by GELight** [kaermorchen/ember-cli-bootstrap-4#8]
Hi,

I works on a Ember based page and try to use your package for bootstrap 4.
The CSS side is fine but the Javascripts of the Bootstrap 4 Framework is not included in my Ember App.
What I have to do to include the related javascripts with your addon?

Greetings, Mario

**Comment by alexvermeulen** [comment]
Also wondering the same thing!

**Comment by alexvermeulen** [comment]
Ah ha! I found this closed issue: https://github.com/kaermorchen/ember-cli-bootstrap-4/issues/5

@GELight You can import the javascript files by adding the following to your `ember-cli-build.js`
```
app.import('bower_components/tether/dist/js/tether.min.js');
app.import('bower_components/bootstrap/dist/js/bootstrap.min.js');
```

It would be helpful if this was mentioned in the README

**Comment by GELight** [comment]
This also is/was my solution in my application.
I thought that the plugin set these dependencies automatically.

This would be very nice. :) But your solution is working too. 
Thank you ...

**Comment by kaermorchen** [comment]
#5
