### ISSUE TITLE
ember-resolver error when importing bv4 via bower

### ISSUE THREAD

**Issue by gokatz** [kaermorchen/ember-cli-bootstrap-4#9]
When I'm trying to import the bootstrap V4 alpha 6 into my ember-cli-build file (app.import) via bower, the `ember build` throws an error `Could not find module 'ember-resolver' imported from 'myapp/resolver'`. But it works fine when importing v3. Any idea ???

**Comment by kaermorchen** [comment]
Which version of ember-cli do you  use?

Do you install Bootstrap v4 like this `bower install bootstrap#v4.0.0-alpha.6 --save`?

**Comment by gokatz** [comment]
Yup..

**Comment by kaermorchen** [comment]
I don't know how to help you, when I do `ember build` my test project works as expected.

**Comment by kaermorchen** [comment]
It should be fixed in latest version (0.3.0).

Feel free to reopen it.
